import React, { useState } from "react";
import GroupCard from "./GroupCard";
import {
  css,
  html,
  javascript,
  next,
  nodejs,
  python,
  react,
  reactnative,
  redux,
  sass,
  tailwind,
  typescript,
} from "../assets";

const CommunityGroups = () => {
  const [toggle, setToggle] = useState(false);
  return (
    <div className="flex flex-col bg-gray-100 sm:pt-10 items-center">
      <div className="sm:text-6xl text-3xl text-center font-bold sm:p-6 p-4 text-blue-900">
        FullStack Developers Community
      </div>
      <div className="w-[85%] sm:w-[60%] text-center font-normal text-gray-600 lg:text-3xl sm:text-2xl text:xl sm:p-6 p-2">
        Full-stack developers work as part of the larger software development
        community. Full-stack developers specialize in web development, but
        these same web technologies now power many apps that run on smartphones
        and tablets. Full-stack developers often specialize in a particular set
        of back-end programming languages and tools.
      </div>
      <div className="grid xxl:grid-cols-4 xl:grid-cols-3 lg:grid-cols-2 grid-cols-1 bg-gray-100 sm:mb-10 mb-4 mt-5 w-[85%]">
        <GroupCard
          title={"HTML Group"}
          description="HTML stands for HyperText Markup Language. It is used to design web
          pages using the markup language. HTML is the combination of Hypertext
          and Markup language. Hypertext defines the link between the web pages
          and markup language defines the text document within the tag that
          define the structure of web pages."
          image={html}
          peopleinagroup={21012}
        />
        <GroupCard
          title={"CSS Group"}
          description="CSS is the language we use to style a Web page. What is CSS? CSS stands for Cascading Style Sheets CSS describes how HTML elements are to be displayed on screen, paper. A CSS rule consists of a selector and a declaration block: The selector points to the HTML element to style (h1)."
          image={css}
          peopleinagroup={18972}
        />
        <GroupCard
          title={"JavaScript Group"}
          description="JavaScript is the Programming Language for the Web. JavaScript can update and change both HTML and CSS. JavaScript can calculate, manipulate and validate data. It is an interpreted programming language with object-oriented capabilities. JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java.
          "
          image={javascript}
          peopleinagroup={15656}
        />
        <GroupCard
          title={"React JS Group"}
          description="React (also known as React.js or ReactJS) is a free and open-source front-end JavaScript library for building user interfaces based on UI components. It is maintained by Meta (formerly Facebook) and a community of individual developers and companies.
          ReactJS is a declarative, efficient, and flexible JavaScript library for building reusable UI components."
          image={react}
          peopleinagroup={12333}
        />
        <GroupCard
          title={"Next JS Group"}
          description="Next.js is a javascript framework built with react js, webpack, and babel. Next.js helps developers quickly create static generation (SSG) and server-side rendering (SSR) websites. Next.js helps to optimize your website. Recently lots of developers have been working with Next.js."
          image={next}
          peopleinagroup={7561}
        />
        <GroupCard
          title={"Tailwind CSS Group"}
          description="Tailwind CSS is basically a Utility first CSS framework for building rapid custom UI. It is a highly customizable, low-level CSS framework that gives you all of the building blocks that you need. Also, it is a cool way to write inline styling and achieve an awesome interface without writing a single line of your own CSS."
          image={tailwind}
          peopleinagroup={5355}
        />

        {toggle && (
          <>
            <GroupCard
              title={"React Native Group"}
              description="React Native is an open source JavaScript Mobile framework from Facebook specially designed to build native mobile apps for iOS and Android. React Native is based on ReactJS JavaScript library that helps to build the user interface for mobile platforms. React Native can be directly used inside an existing IOS or android app or you can build a native app right from scratch."
              image={reactnative}
              peopleinagroup={2109}
            />
            <GroupCard
              title={"Redux Group"}
              description="Redux is an open-source JavaScript library for managing the application state. Redux is commonly used with libraries such as Angular or React to build user interfaces. It was created by Andrew Clark and Dan Abramov. It becomes difficult to manage the state of each component in the application when the size of the application becomes extremely large. It helps in updating and maintaining the state of each component in the application."
              image={redux}
              peopleinagroup={21012}
            />
            <GroupCard
              title={"SASS Group"}
              description="HTML stands for HyperText Markup Language. It is used to design web
              pages using the markup language. HTML is the combination of Hypertext
              and Markup language. Hypertext defines the link between the web pages
              and markup language defines the text document within the tag that
              define the structure of web pages."
              image={sass}
              peopleinagroup={3121}
            />
            <GroupCard
              title={"TypeScript Group"}
              description="TypeScript is a strongly typed, object oriented, compiled language. It was designed by Anders Hejlsberg (designer of C#) at Microsoft. TypeScript is both a language and a set of tools. TypeScript is a typed superset of JavaScript compiled to JavaScript. In other words, TypeScript is JavaScript plus some additional features."
              image={typescript}
              peopleinagroup={1210}
            />
            <GroupCard
              title={"Node JS Group"}
              description="Node.js is an open-source, cross-platform, JavaScript runtime environment that executes JavaScript code outside of a web browser. Node.js is a popular, lightweight web framework for beginners, and it is used by many big companies like Netflix and Uber."
              image={nodejs}
              peopleinagroup={24567}
            />
            <GroupCard
              title={"DJANGO Group"}
              description="Django is a Python-based web framework that allows you to quickly create efficient web applications. It is also called batteries included framework because Django provides built-in features for everything including Django Admin Interface, default database – SQLlite3, etc."
              image={python}
              peopleinagroup={31237}
            />
          </>
        )}
      </div>
      <button
        type="button"
        value={toggle}
        onClick={(e) => setToggle(!toggle)}
        className="sm:py-4 py-2 sm:px-6 px-3 mt-3 mb-10 rounded-xl bg-blue-500 hover:bg-pink-400 text-white font-semibold sm:text-2xl text-xl"
      >
        {toggle ? "Show less" : "Explore More"}
      </button>
    </div>
  );
};

export default CommunityGroups;
